#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

NAME=baidupcs-web
PROG=/usr/bin/baidupcs-web

_info() {
	logger -p daemon.info -t "$NAME" "$*"
}

_err() {
	logger -p daemon.err -t "$NAME" "$*"
}

_make_dir() {
	local d
	for d in "$@"; do
		if [ ! -d "$d" ]; then
			mkdir -p "$d" 2>/dev/null || return 1
		fi
	done

	return 0
}

_create_file() {
	touch "$@" 2>/dev/null
}

_change_owner() {
	local u="$1"; shift

	local d
	for d in "$@"; do
		if [ -f "$d" ]; then
			chown "$u" "$d" 2>/dev/null || return 1
		elif [ -d "$d" ]; then
			chown -R "$u" "$d" 2>/dev/null || return 1
		fi
	done

	return 0
}

_change_file_mode() {
	local mod="$1"; shift
	chmod "$mod" "$@" 2>/dev/null
}

_reset_dir_mode() {
	local d
	for d in "$@"; do
		if [ -d "$d" ]; then
			find "$d" -type d -exec chmod 755 {} \; 2>/dev/null
			find "$d" -type f -exec chmod 644 {} \; 2>/dev/null
		fi
	done
}

append_options() {
	local o; local v
	for o in "$@"; do
		v="$(eval echo "\$$o")"
		[ -n "$v" ] && \
			echo "${o//_/-}=$v" >>"$config_file_tmp"
	done
}

append_setting() {
	local s="$1"
	[ -n "$s" ] && \
		echo "$s" >>"$config_file_tmp"
}

append_header() {
	local h="$1"
	[ -n "$h" ] && \
		echo "header=\"$h\"" >>"$config_file_tmp"
}

baidupcs_validate() {
	uci_load_validate "$NAME" baidupcs-web "$1" "$2" \
		'enabled:bool:0' \
		'port:uinteger:5299' \
		'download_dir:string' \
		'max_download_rate:uinteger:0' \
		'max_upload_rate:uinteger:0' \
		'max_download_load:uinteger:1' \
		'max_parallel:uinteger:8' \
		'aria2:bool:0' \
		'aria2_RPC:string:http://127.0.0.1:6800/jsonrpc' \
		'aria2_secret:string'
}

baidupcs_start() {
	local section="$1"
	[ "$2" = "0" ] || { _err "Validation failed."; return 1; }

	[ "$enabled" = "1" ] || { _info "Instance \"$section\" disabled."; return 1; }

	# check directory existence before creating it
	if [ ! -e "$download_dir" ]; then
		_make_dir "$download_dir" || {
			_err "Can't create download dir: $download_dir"
			return 1
		}
	fi

	baidupcs-web config set                         \
	--savedir               "$download_dir"         \
	--max_download_rate	"$max_download_rate"	\
	--max_upload_rate	"$max_upload_rate"	\
	--max_download_load	"$max_download_load"	\
	--max_parallel		"$max_parallel"		\
	--max_upload_parallel	"$max_upload_parallel"	\
	>/dev/null 2>&1

	procd_open_instance "$NAME.$section"
	procd_set_param command "$PROG"
	[ $aria2 == '1' ] && procd_append_param command -a -au "${aria2_RPC}" -as "${aria2_secret}" || procd_append_param command --port "$port" --access

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_add_jail "$NAME.$section" log
	procd_add_jail_mount_rw "$download_dir"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
	procd_add_validation baidupcs_validate
}

start_service() {
	config_load "$NAME"
	config_foreach baidupcs_validate "baidupcs-web" baidupcs_start
}