name: Lede Checker

env:
  LEDE_URL: https://github.com/coolsnowwolf/lede.git
  LEDE_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          git clone --depth 1 $LEDE_URL -b $LEDE_BRANCH .
          echo "::set-output name=commitHash::$(git rev-parse HEAD)"

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v2
        with:
          path: .commitHash
          key: HEAD-${{ steps.getHash.outputs.commitHash }}

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: Trigger build OpenWRT
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: GeekEast/trigger-open-pr-workflow@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          workflow_filename: 'build-openwrt.yml'