name: Passwall Checker

env:
  PASSWALL_URL: https://github.com/xiaorouji/openwrt-passwall.git
  PASSWALL_BRANCH: packages
  PASSWALL_BRANCH2: luci

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

jobs:
  passwall:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          git clone --depth 1 $PASSWALL_URL -b $PASSWALL_BRANCH .
          echo "::set-output name=commitHash::$(git rev-parse HEAD)"

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v2
        with:
          path: .commitHash
          key: HEAD-${{ steps.getHash.outputs.commitHash }}

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: Trigger build Bypass
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: GeekEast/trigger-open-pr-workflow@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          workflow_filename: 'build-bypass.yml'

  passwall-luci:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          git clone --depth 1 $PASSWALL_URL -b $PASSWALL_BRANCH2 .
          echo "::set-output name=commitHash::$(git rev-parse HEAD)"

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v2
        with:
          path: .commitHash
          key: HEAD-${{ steps.getHash.outputs.commitHash }}

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: Trigger build Bypass
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: GeekEast/trigger-open-pr-workflow@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          workflow_filename: 'build-bypass.yml'